//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbPrCrmEntities : DbContext
    {
        public DbPrCrmEntities()
            : base("name=DbPrCrmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EmailsQueue> EmailsQueues { get; set; }
        public virtual DbSet<EmailsSend> EmailsSends { get; set; }
        public virtual DbSet<JBI> JBIs { get; set; }
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<TextBox> TextBoxes { get; set; }
    }
}
