//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRService
{
    using System;
    using System.Collections.Generic;
    
    public partial class TextBox
    {
        public byte[] Upsize_ts { get; set; }
        public int ActivityId { get; set; }
        public int TextBoxId { get; set; }
        public string Text { get; set; }
        public Nullable<bool> Bold { get; set; }
        public Nullable<int> FontSize { get; set; }
        public string Color { get; set; }
    }
}
