//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbPrCrmEntities : DbContext
    {
        public DbPrCrmEntities()
            : base("name=DbPrCrmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LoginLog> LoginLogs { get; set; }
        public virtual DbSet<JBI> JBIs { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<ActivityJBI> ActivityJBIs { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<TextBox> TextBoxes { get; set; }
        public virtual DbSet<UsersCompany> UsersCompanies { get; set; }
        public virtual DbSet<EmailsQueue> EmailsQueues { get; set; }
        public virtual DbSet<Template> Templates { get; set; }
    }
}
