//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int Moneln { get; set; }
        public string Email { get; set; }
        public Nullable<long> UserId { get; set; }
        public string Pass { get; set; }
        public string Phone { get; set; }
        public string UserName { get; set; }
    }
}
